"""empty message

Revision ID: 0b27556a8893
Revises: 16f2b372d391
Create Date: 2019-10-14 12:58:41.051855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b27556a8893'
down_revision = '16f2b372d391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attachments', sa.Column('file_path', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'Attachments', 'Items', ['item_id'], ['id'])
    # ### end Alembic commands ###
	
	
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'Attachments', type_='foreignkey')
    # op.drop_column('Attachments', 'file_path')
    # ### end Alembic commands ###
	pass