"""empty message

Revision ID: 16f2b372d391
Revises: fe3a5e1ca4da
Create Date: 2019-10-11 08:44:53.598788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f2b372d391'
down_revision = 'fe3a5e1ca4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attachments', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Attachments', 'Items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Attachments', type_='foreignkey')
    op.drop_column('Attachments', 'item_id')
    # ### end Alembic commands ###
