"""empty message

Revision ID: 2a477246d962
Revises: 989c56ee78c1
Create Date: 2019-07-30 11:00:12.394949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a477246d962'
down_revision = '989c56ee78c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('Items', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Items', 'Users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'Items', 'Users', ['created_by_id'], ['id'])
    op.add_column('Review', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('Review', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Review', 'Users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'Review', 'Users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'Review', type_='foreignkey')
    # op.drop_constraint(None, 'Review', type_='foreignkey')
    # op.drop_column('Review', 'updated_by_id')
    # op.drop_column('Review', 'created_by_id')
    # op.drop_constraint(None, 'Items', type_='foreignkey')
    # op.drop_constraint(None, 'Items', type_='foreignkey')
    # op.drop_column('Items', 'updated_by_id')
    # op.drop_column('Items', 'created_by_id')
    # ### end Alembic commands ###
