"""empty message

Revision ID: 97db06f8278f
Revises: 0b27556a8893
Create Date: 2019-11-11 15:05:55.671407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97db06f8278f'
down_revision = '0b27556a8893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'Attachments', 'Items', ['item_id'], ['id'])
    # ### end Alembic commands ###
	pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'Attachments', type_='foreignkey')
    # ### end Alembic commands ###
	pass