"""empty message

Revision ID: cca343534ae9
Revises: 4da0d477382b
Create Date: 2019-08-20 12:54:20.911920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca343534ae9'
down_revision = '4da0d477382b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('address_line_1', sa.Text(), nullable=False),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('address_line_3', sa.Text(), nullable=True),
    sa.Column('postcode', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('main_phone_number', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Address')
    # ### end Alembic commands ###
