"""empty message

Revision ID: f8609e5d11d7
Revises: c26c7aee2939
Create Date: 2020-01-21 12:51:06.455176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8609e5d11d7'
down_revision = 'c26c7aee2939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # op.add_column('Users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # op.add_column('Users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('avatar')

    # op.drop_column('Users', 'avatar')
    # op.drop_column('Users', 'is_deleted')
    # ### end Alembic commands ###
