"""empty message

Revision ID: fe3a5e1ca4da
Revises: cca343534ae9
Create Date: 2019-10-08 22:53:45.568166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3a5e1ca4da'
down_revision = 'cca343534ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_extension', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Attachments')
    # ### end Alembic commands ###
